import Head from 'next/head';
import Navbar from '@components/Navbar';
import dynamic from 'next/dynamic';

const MapWithNoSSR = dynamic(() => import('@components/Map'), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="dark:bg-neutral-900 min-h-screen">
        <div className="max-w-5xl mx-auto p-4">
          <MapWithNoSSR />
        </div>
      </main>
    </div>
  )
}
